buildscript {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

version = project.modVersion
group = project.mavenGroup
archivesBaseName = project.artifactBaseName

sourceCompatibility = targetCompatibility = JavaVersion.VERSION_1_8

minecraft {
    version = project.forgeVersion
    runDir = 'run'
    mappings = project.mcpMappings
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('mcmod.info') {
        expand 'version': project.version
    }
}

jar {
    manifest {
        attributes(
            'Specification-Title': 'Pug Alt Manager',
            'Specification-Version': project.version,
            'Implementation-Title': project.name,
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'PugrillaDev'
        )
    }
}
